
paths:
  dataset_dir: /Users/cschaefe/datasets/MFA_LJ
  data_dir: dfa_data
  checkpoint_dir: dfa_checkpoints
  precomputed_mels: null # Optional: pre-computed mels

audio:
  sample_rate: 22050
  n_filters: 1024
  n_mels: 80
  win_length: 1024
  hop_length: 256
  fmin: 0
  fmax: 8000

model:
  lstm_dim: 256
  conv_dim: 256

training:
  learning_rate: 0.0001
  batch_size: 8
  epochs: 1000
  plot_steps: 1000
  checkpoint_steps: 10_000