
paths:
  dataset_dir: LJSpeech-1.1                    # path to dataset containing wavs
  metadata_path: LJSpeech-1.1/metadata.csv     # path to LJSpeech-style metafile with format: id|text
  precomputed_mels:  /Users/cschaefe/workspace/ForwardTacotron/data/mel                          # replaces dataset_dir if set and points to already preprocessed mels
  data_dir: dfa_data                           # directory to store preprocessed data
  checkpoint_dir: dfa_checkpoints              # directory for model checkpoints and tensorboard

audio:
  sample_rate: 22050
  n_filters: 1024
  n_mels: 80
  win_length: 1024
  hop_length: 256
  fmin: 0
  fmax: 8000

preprocessing:
  mel_dim_last: false # whether precomputed mels have mel channels as last dimension

model:
  lstm_dim: 512
  conv_dim: 512

durations:
  method: 'dijkstra' # options: [dijkstra, beam]

training:
  learning_rate: 0.0001
  batch_size: 32
  epochs: 1000
  plot_steps: 1000
  checkpoint_steps: 10_000