
paths:
  dataset_dir: "/home/sysgen/chris/data/ASVoice4_english"
  metadata_path: "/home/sysgen/chris/data/ASVoice4_english/metafile_en_replaced_phonemized.txt"
  data_dir: dfa_data
  checkpoint_dir: dfa_checkpoints
  precomputed_mels:

audio:
  sample_rate: 22050
  n_filters: 1024
  n_mels: 80
  win_length: 1024
  hop_length: 256
  fmin: 0
  fmax: 8000

preprocessing:
  mel_dim_last: false # whether precomputed mels have mel channels as last dimension

model:
  lstm_dim: 32
  conv_dim: 32

durations:
  method: 'dijkstra' # options: [dijkstra, beam]

training:
  learning_rate: 0.0001
  batch_size: 8
  epochs: 2
  plot_steps: 1000
  checkpoint_steps: 10_000
